import path from "node:path";

const fixturesDir = path.resolve(import.meta.dir, "fixtures");

const fixtureNames = {
  agenticWorkflowLike: "agentic-workflow-like",
  alpineCiLike: "alpine-ci-like",
  angularCacheLike: "angular-cache-like",
  angularCacheOk: "angular-cache-ok",
  angularMaterialRootImportLike: "angular-material-root-import-like",
  antDesignIconsRootImportLike: "ant-design-icons-root-import-like",
  antdRootImportLike: "antd-root-import-like",
  apiDeployArmRunnerLike: "api-deploy-arm-runner-like",
  apiDeployArmRunnerOk: "api-deploy-arm-runner-ok",
  avoidCDriveOnWindowsRunnerLike: "avoid-c-drive-on-windows-runner-like",
  avoidCDriveOnWindowsRunnerOk: "avoid-c-drive-on-windows-runner-ok",
  avoidDockerImageViaUsesLike: "avoid-docker-image-via-uses-like",
  avoidDockerImageViaUsesOk: "avoid-docker-image-via-uses-ok",
  barrelFileLike: "barrel-file-like",
  barrelFileSkipOxlintLike: "barrel-file-skip-oxlint-like",
  blobNoneAgenticDocsEditLike: "blob-none-agentic-docs-edit-like",
  blobNoneBuildWithFlagsLike: "blob-none-build-with-flags-like",
  blobNoneChangelogActionLike: "blob-none-changelog-action-like",
  blobNoneGhReleaseLike: "blob-none-gh-release-like",
  blobNoneHeavyPublishLike: "blob-none-heavy-publish-like",
  blobNoneLike: "blob-none-like",
  blobNoneOk: "blob-none-ok",
  blobNonePrepareFetchLike: "blob-none-prepare-fetch-like",
  buildkiteTimeoutLike: "buildkite-timeout-like",
  buildkiteTimeoutMultiLike: "buildkite-timeout-multi-like",
  buildkiteTimeoutOk: "buildkite-timeout-ok",
  gitlabCiTimeoutLike: "gitlab-ci-timeout-like",
  gitlabCiTimeoutOk: "gitlab-ci-timeout-ok",
  circleciFullCloneLike: "circleci-full-clone-like",
  circleciFullCloneOk: "circleci-full-clone-ok",
  circleciFullCloneOkUsesHistory: "circleci-full-clone-ok-uses-history",
  depotCiLike: "depot-ci-like",
  cargoBuildBeforeTestLike: "cargo-build-before-test-like",
  cargoBuildBeforeTestOk: "cargo-build-before-test-ok",
  cdkBucketDeploymentMemoryLike: "cdk-bucket-deployment-memory-like",
  cdkBucketDeploymentMemoryOk: "cdk-bucket-deployment-memory-ok",
  cleanNoFindings: "clean-no-findings",
  datadogLambdaLike: "datadog-lambda-like",
  datadogLambdaOk: "datadog-lambda-ok",
  dbIoConfigLike: "db-io-config-like",
  dbIoConfigOk: "db-io-config-ok",
  dateFnsRootImportLike: "date-fns-root-import-like",
  ddTrace: "dd-trace-js",
  deepCheckoutExcessiveLike: "deep-checkout-excessive-like",
  deepCheckoutExcessiveOkUsesHistory: "deep-checkout-excessive-ok-uses-history",
  deepCheckoutExcessiveOkRelease: "deep-checkout-excessive-ok-release",
  deepCheckoutMutatingAction: "deep-checkout-mutating-action",
  deepCheckoutOpaqueScript: "deep-checkout-opaque-script",
  deepCheckoutRebasePush: "deep-checkout-rebase-push",
  deepCheckoutReleaseLike: "deep-checkout-release-like",
  deepCheckoutVersionLike: "deep-checkout-version-like",
  dependencyCacheLike: "dependency-cache-like",
  disabledAgenticWorkflow: "disabled-agentic-workflow",
  dockerBuildContextComposeLike: "docker-build-context-compose-like",
  dockerBuildContextLike: "docker-build-context-like",
  dockerBuildContextOk: "docker-build-context-ok",
  dockerBuildContextSubdirLike: "docker-build-context-subdir-like",
  dockerBuildLoadTrueComposeOk: "docker-build-load-true-compose-ok",
  dockerBuildLoadTrueDynamicOk: "docker-build-load-true-dynamic-ok",
  dockerBuildLoadTrueLike: "docker-build-load-true-like",
  dockerBuildLoadTrueOk: "docker-build-load-true-ok",
  dockerBuildWithoutLayerCacheDepotOk: "docker-build-without-layer-cache-depot-ok",
  dockerBuildWithoutLayerCacheLike: "docker-build-without-layer-cache-like",
  dockerBuildWithoutLayerCacheNocacheOk: "docker-build-without-layer-cache-nocache-ok",
  dockerBuildWithoutLayerCacheOk: "docker-build-without-layer-cache-ok",
  dockerBunCiOk: "docker-bun-ci-ok",
  dockerBunUnfrozenLike: "docker-bun-unfrozen-like",
  dockerGoCacheOk: "docker-go-cache-ok",
  dockerGoUncachedLike: "docker-go-uncached-like",
  dockerGradleCacheOk: "docker-gradle-cache-ok",
  dockerGradleUncachedLike: "docker-gradle-uncached-like",
  dockerMavenCacheOk: "docker-maven-cache-ok",
  dockerMavenUncachedLike: "docker-maven-uncached-like",
  dockerNpmInstallLockfileLike: "docker-npm-install-lockfile-like",
  dockerNpmInstallSugarLike: "docker-npm-install-sugar-like",
  dockerPnpmFrozenOk: "docker-pnpm-frozen-ok",
  dockerPnpmUnfrozenLike: "docker-pnpm-unfrozen-like",
  dockerRubyCacheOk: "docker-ruby-cache-ok",
  dockerRubyUncachedLike: "docker-ruby-uncached-like",
  dockerRustCacheOk: "docker-rust-cache-ok",
  dockerRustUncachedLike: "docker-rust-uncached-like",
  dockerUvFrozenOk: "docker-uv-frozen-ok",
  dockerUvUnfrozenLike: "docker-uv-unfrozen-like",
  dockerYarnImmutableOk: "docker-yarn-immutable-ok",
  dockerYarnUnfrozenLike: "docker-yarn-unfrozen-like",
  duplicationLike: "duplication-like",
  elixirSecurityAdvisoriesOk: "elixir-security-advisories-ok",
  effectRootImportLike: "effect-root-import-like",
  explicitImportExtensionsLargeViteLike: "explicit-import-extensions-large-vite-like",
  explicitImportExtensionsSmallViteLike: "explicit-import-extensions-small-vite-like",
  fontAwesomeIconPackRootImportLike: "font-awesome-icon-pack-root-import-like",
  formattingLike: "formatting-like",
  formattingPluginLike: "formatting-plugin-like",
  geminiCli: "gemini-cli",
  gradleCacheLike: "gradle-cache-like",
  gradleCacheOk: "gradle-cache-ok",
  headlessUiFloatReactRootImportLike: "headlessui-float-react-root-import-like",
  headlessUiReactRootImportLike: "headlessui-react-root-import-like",
  heroiconsGroupedImportLike: "heroicons-grouped-import-like",
  huskyComplexLike: "husky-complex-like",
  huskyLike: "husky-like",
  huskyModernLike: "husky-modern-like",
  iamtrailLike: "iamtrail-like",
  importPluginLike: "import-plugin-like",
  importXLike: "import-x-like",
  lightweightNodeToolingLike: "lightweight-node-tooling-like",
  lightweightPythonToolingLike: "lightweight-python-tooling-like",
  lodashEsRootImportLike: "lodash-es-root-import-like",
  lucideAngularIconsRegistryLike: "lucide-angular-icons-registry-like",
  lucideDynamicIconLike: "lucide-dynamic-icon-like",
  macosBrewUpdateLike: "macos-brew-update-like",
  macosBrewUpdateOk: "macos-brew-update-ok",
  macosXcodeInstallLike: "macos-xcode-install-like",
  macosXcodeInstallOk: "macos-xcode-install-ok",
  manualHeavyLike: "manual-heavy-like",
  materialUiV4RootImportLike: "material-ui-v4-root-import-like",
  mypyMilestoneLike: "mypy-milestone-like",
  mypyMilestoneOk: "mypy-milestone-ok",
  mypyProductionBundleLike: "mypy-production-bundle-like",
  mypyProductionBundleOk: "mypy-production-bundle-ok",
  matrixShardLike: "matrix-shard-like",
  matrixShardOk: "matrix-shard-ok",
  metaCheckLike: "meta-check-like",
  muiBarrelImportLike: "mui-barrel-import-like",
  muiCoreRootImportLike: "mui-core-root-import-like",
  nativeBuildRiskLike: "native-build-risk-like",
  nativeBuildRiskOk: "native-build-risk-ok",
  nextCacheLike: "next-cache-like",
  nextCacheOk: "next-cache-ok",
  nextjs12MinorLike: "nextjs-12-minor-like",
  nextjs12MinorOk: "nextjs-12-minor-ok",
  nextjs13MinorLike: "nextjs-13-minor-like",
  nextjs13MinorOk: "nextjs-13-minor-ok",
  nextjs14MinorLike: "nextjs-14-minor-like",
  nextjs14MinorOk: "nextjs-14-minor-ok",
  npmCiOk: "npm-ci-ok",
  npmCiOverNpmInstallLike: "npm-ci-over-npm-install-like",
  nxCacheLike: "nx-cache-like",
  nxCacheOk: "nx-cache-ok",
  nxCopilotNoCloudLike: "nx-copilot-no-cloud-like",
  osPackageInstallLike: "os-package-install-like",
  osPackageInstallOk: "os-package-install-ok",
  portableToolingArmRunnerLike: "portable-tooling-arm-runner-like",
  portableToolingArmRunnerOk: "portable-tooling-arm-runner-ok",
  preinstalledCliLike: "preinstalled-cli-like",
  preferPydanticV2Like: "prefer-pydantic-v2-like",
  preferPydanticV2Ok: "prefer-pydantic-v2-ok",
  prettierEslintLike: "prettier-eslint-like",
  prettierThroughEslintLike: "prettier-through-eslint-like",
  pythonToolingLike: "python-tooling-like",
  qemuArmLike: "qemu-arm-like",
  qemuArmNativeRunnerOk: "qemu-arm-native-runner-ok",
  qemuMultiPlatformLike: "qemu-multi-platform-like",
  qemuShellBuildxLike: "qemu-shell-buildx-like",
  qemuUnusedLike: "qemu-unused-like",
  ramdaRootImportLike: "ramda-root-import-like",
  reactBootstrapRootImportLike: "react-bootstrap-root-import-like",
  reactIconsGroupedImportLike: "react-icons-grouped-import-like",
  reactUseRootImportLike: "react-use-root-import-like",
  rechartsRootImportLike: "recharts-root-import-like",
  releaseGuardFailureCancelledLike: "release-guard-failure-cancelled-like",
  releaseGuardLike: "release-guard-like",
  releaseGuardManyLike: "release-guard-many-like",
  releaseGuardOk: "release-guard-ok",
  releaseGuardOptionalSkipOk: "release-guard-optional-skip-ok",
  releaseGuardReportingOk: "release-guard-reporting-ok",
  renovateAwsSdkGroupingAutomergeSkip: "renovate-aws-sdk-grouping-automerge-skip",
  renovateAwsSdkGroupingConfigRecommendedSkip: "renovate-aws-sdk-grouping-config-recommended-skip",
  renovateAwsSdkGroupingExtendsSkip: "renovate-aws-sdk-grouping-extends-skip",
  renovateAwsSdkGroupingGroupedOk: "renovate-aws-sdk-grouping-grouped-ok",
  renovateAwsSdkGroupingLike: "renovate-aws-sdk-grouping-like",
  renovateAwsSdkGroupingOk: "renovate-aws-sdk-grouping-ok",
  renovateCdkDepsGroupingAutomergeSkip: "renovate-cdk-deps-grouping-automerge-skip",
  renovateCdkDepsGroupingConfigRecommendedConstructsLike:
    "renovate-cdk-deps-grouping-config-recommended-constructs-like",
  renovateCdkDepsGroupingConfigRecommendedSkip:
    "renovate-cdk-deps-grouping-config-recommended-skip",
  renovateCdkDepsGroupingExtendsSkip: "renovate-cdk-deps-grouping-extends-skip",
  renovateCdkDepsGroupingGroupedOk: "renovate-cdk-deps-grouping-grouped-ok",
  renovateCdkDepsGroupingLike: "renovate-cdk-deps-grouping-like",
  renovateCdkDepsGroupingOk: "renovate-cdk-deps-grouping-ok",
  renovateRebaseWhenAutomergeSkip: "renovate-rebase-when-automerge-skip",
  renovateRebaseWhenConfigRecommendedLike: "renovate-rebase-when-config-recommended-like",
  renovateRebaseWhenExtendsSkip: "renovate-rebase-when-extends-skip",
  renovateRebaseWhenGithubExtendsSkip: "renovate-rebase-when-github-extends-skip",
  renovateRebaseWhenGroupSkip: "renovate-rebase-when-group-skip",
  renovateRebaseWhenLike: "renovate-rebase-when-like",
  renovateRebaseWhenLocalExtendsLike: "renovate-rebase-when-local-extends-like",
  renovateRebaseWhenOk: "renovate-rebase-when-ok",
  rustNextestLike: "rust-nextest-like",
  rustNextestOk: "rust-nextest-ok",
  rxjsRootImportLike: "rxjs-root-import-like",
  sampleRepo: "sample-repo",
  scheduledHeavyLike: "scheduled-heavy-like",
  scheduledHeavyOk: "scheduled-heavy-ok",
  setupNodeCacheDependencyPathOk: "setup-node-cache-dependency-path-ok",
  setupNodeCacheDependencyPathUnsetLike: "setup-node-cache-dependency-path-unset-like",
  slimCiLike: "slim-ci-like",
  sparseCheckoutAgenticDocsUpdate: "sparse-checkout-agentic-docs-update",
  sparseCheckoutLike: "sparse-checkout-like",
  sparseCheckoutOk: "sparse-checkout-ok",
  sparseCheckoutOpaqueScriptWithLocalAction: "sparse-checkout-opaque-script-with-local-action",
  sparseCheckoutPreflightFalsePositive: "sparse-checkout-preflight-false-positive",
  stepTimeoutOnlyLike: "step-timeout-only-like",
  storybook10MinorLike: "storybook-10-minor-like",
  storybook10MinorOk: "storybook-10-minor-ok",
  storybook6MinorLike: "storybook-6-minor-like",
  storybook6MinorOk: "storybook-6-minor-ok",
  storybook7MinorLike: "storybook-7-minor-like",
  storybook7MinorOk: "storybook-7-minor-ok",
  storybook8MinorLike: "storybook-8-minor-like",
  storybook8MinorOk: "storybook-8-minor-ok",
  storybook9MinorLike: "storybook-9-minor-like",
  storybook9MinorOk: "storybook-9-minor-ok",
  svgComponentImportLike: "svg-component-import-like",
  swcBabelLike: "swc-babel-like",
  swcBabelOk: "swc-babel-ok",
  swcBabelSkipCustomPlugins: "swc-babel-skip-custom-plugins",
  swcBabelSkipMacros: "swc-babel-skip-macros",
  swcBabelSkipDecorators: "swc-babel-skip-decorators",
  swcBabelSkipEmotion: "swc-babel-skip-emotion",
  swcBabelSkipCorejs: "swc-babel-skip-corejs",
  swcBabelSkipLegacyTargets: "swc-babel-skip-legacy-targets",
  tablerIconsRootImportLike: "tabler-icons-root-import-like",
  tailwindContentBroadGlobLike: "tailwind-content-broad-glob-like",
  tailwindContentMissingLike: "tailwind-content-missing-like",
  tailwindContentNodeModulesLike: "tailwind-content-node-modules-like",
  tailwindContentOk: "tailwind-content-ok",
  tailwindV3LegacyBrowserSkip: "tailwind-v3-legacy-browser-skip",
  tailwindV3Node18Skip: "tailwind-v3-node18-skip",
  tailwindV3UpgradeToolLike: "tailwind-v3-upgrade-tool-like",
  tailwindV3UpgradeToolPluginSkip: "tailwind-v3-upgrade-tool-plugin-skip",
  terraformCacheLike: "terraform-cache-like",
  terraformCacheOk: "terraform-cache-ok",
  terraformGitHubAppAuthLike: "terraform-github-app-auth-like",
  terraformGitHubAppAuthOk: "terraform-github-app-auth-ok",
  terraformGitHubParallelRequestsLike: "terraform-github-parallel-requests-like",
  terraformGitHubParallelRequestsOk: "terraform-github-parallel-requests-ok",
  terraformGitHubSlowResourcesLike: "terraform-github-slow-resources-like",
  terraformGitHubSlowResourcesOk: "terraform-github-slow-resources-ok",
  terraformLockfileMissing: "terraform-lockfile-missing",
  terraformLockfileOk: "terraform-lockfile-ok",
  terraformPagerDutyTeamMembershipVersionLike: "terraform-pagerduty-team-membership-version-like",
  terraformPagerDutyTeamMembershipVersionOk: "terraform-pagerduty-team-membership-version-ok",
  terraformParallelismMissing: "terraform-parallelism-missing",
  terraformParallelismOk: "terraform-parallelism-ok",
  terraformParallelismOkEnv: "terraform-parallelism-ok-env",
  tremorRootImportLike: "tremor-root-import-like",
  tsLoaderForkTsCheckerHappyPackLike: "ts-loader-fork-ts-checker-happy-pack-like",
  tsLoaderForkTsCheckerLike: "ts-loader-fork-ts-checker-like",
  tsLoaderForkTsCheckerOk: "ts-loader-fork-ts-checker-ok",
  tsToolingCustomLike: "ts-tooling-custom-like",
  tsToolingLike: "ts-tooling-like",
  turboCacheLike: "turbo-cache-like",
  turboCacheOk: "turbo-cache-ok",
  typescriptMilestone52Like: "typescript-milestone-52-like",
  typescriptMilestone59Like: "typescript-milestone-59-like",
  typescriptMilestoneLike: "typescript-milestone-like",
  visxRootImportLike: "visx-root-import-like",
  unnecessaryCheckoutArtifactLike: "unnecessary-checkout-artifact-like",
  unnecessaryCheckoutArtifactOk: "unnecessary-checkout-artifact-ok",
  unnecessaryCheckoutArtifactReleaseOk: "unnecessary-checkout-artifact-release-ok",
  unnecessaryCheckoutArtifactGitApplyOk: "unnecessary-checkout-artifact-git-apply-ok",
  unnecessaryCheckoutArtifactCreatePrOk: "unnecessary-checkout-artifact-create-pr-ok",
  vitest3MinorLike: "vitest-3-minor-like",
  vitest3MinorOk: "vitest-3-minor-ok",
  wastefulNpmGlobalInstallLike: "wasteful-npm-global-install-like",
  wastefulNpmGlobalInstallOk: "wasteful-npm-global-install-ok",
  wastefulPackageInstallInContainerLike: "wasteful-package-install-in-container-like",
  wastefulPackageInstallInContainerOk: "wasteful-package-install-in-container-ok",
  webpack5RspackLike: "webpack5-rspack-like",
  webpack5RspackOk: "webpack5-rspack-ok",
  webpack5RspackSkipDevserver: "webpack5-rspack-skip-devserver",
  webpack5RspackSkipHooks: "webpack5-rspack-skip-hooks",
  webpack5RspackSkipPlugins: "webpack5-rspack-skip-plugins",
  workerTuningLike: "worker-tuning-like",
  workerTuningOk: "worker-tuning-ok",
  workflowEfficiencyLike: "workflow-efficiency-like",
  toxWithoutToxUvLike: "tox-without-tox-uv-like",
  toxWithoutToxUvOk: "tox-without-tox-uv-ok",
  toxWithoutToxUvSkipNoTox: "tox-without-tox-uv-skip-no-tox",
  toxWithoutToxUvRepoLike: "tox-without-tox-uv-repo-like",
  toxWithoutToxUvRepoOk: "tox-without-tox-uv-repo-ok",
  hatchWithoutUvInstallerLike: "hatch-without-uv-installer-like",
  hatchWithoutUvInstallerOk: "hatch-without-uv-installer-ok",
  hatchWithoutUvInstallerRepoLike: "hatch-without-uv-installer-repo-like",
  hatchWithoutUvInstallerRepoOk: "hatch-without-uv-installer-repo-ok",
  pdmWithoutUseUvLike: "pdm-without-use-uv-like",
  pdmWithoutUseUvOk: "pdm-without-use-uv-ok",
  pdmWithoutUseUvRepoLike: "pdm-without-use-uv-repo-like",
  pdmWithoutUseUvRepoOk: "pdm-without-use-uv-repo-ok",
  preferUvPipOverPipLike: "prefer-uv-pip-over-pip-like",
  preferUvPipOverPipOk: "prefer-uv-pip-over-pip-ok",
  noxWithoutUvBackendLike: "nox-without-uv-backend-like",
  noxWithoutUvBackendOk: "nox-without-uv-backend-ok",
  noxWithoutUvBackendRepoLike: "nox-without-uv-backend-repo-like",
  noxWithoutUvBackendRepoOk: "nox-without-uv-backend-repo-ok",
  npmWorkspacesLike: "npm-workspaces-like",
  npmWorkspacesOk: "npm-workspaces-ok",
  vercelJsonLike: "vercel-json-like",
  vercelJsonNpmRunLike: "vercel-json-npm-run-like",
  vercelJsonMakeLike: "vercel-json-make-like",
  vercelJsonOk: "vercel-json-ok",
  wranglerTomlLike: "wrangler-toml-like",
  wranglerTomlOk: "wrangler-toml-ok",
  vercelJsonPipLike: "vercel-json-pip-like",
  wranglerTomlPipLike: "wrangler-toml-pip-like",
  amplifyYmlLike: "amplify-yml-like",
  amplifyYmlOk: "amplify-yml-ok",
} as const;

const cache = new Map<string, string>();

function resolve(key: string): string {
  let cached = cache.get(key);
  if (!cached) {
    cached = path.resolve(fixturesDir, key);
    cache.set(key, cached);
  }
  return cached;
}

export const fixtures = new Proxy<{ [K in keyof typeof fixtureNames]: string }>(
  {} as { [K in keyof typeof fixtureNames]: string },
  {
    get(_, key: string) {
      const name = (fixtureNames as Record<string, string>)[key];
      if (!name) {
        return undefined as unknown as string;
      }
      return resolve(name);
    },
    ownKeys() {
      return Reflect.ownKeys(fixtureNames) as string[];
    },
    getOwnPropertyDescriptor() {
      return { enumerable: true, configurable: true };
    },
  },
);
