import type { AnalysisWarning, Diagnostic, RuleMeta } from "../types.ts";
import type { RepositorySignals } from "../repository-signals-types.ts";
import { RepositoryScanContext } from "../repository-scan-context.ts";
import { buildRepositoryDiagnostic } from "./diagnostics.ts";
import { collectEmbeddedOxlintDiagnosticsByCode } from "./embedded-oxlint.ts";
import type { DiagnosticOp } from "../rules/shared/diagnostic-ops.ts";
import { applyOps } from "../rules/shared/diagnostic-ops.ts";

const barrelFileMeta = {
  id: "detected-large-barrel-file",
  severity: "warning",
  confidence: "high",
  docsPath: "docs/rules/detected-large-barrel-file.md",
} satisfies RuleMeta;

async function looksLikeJavaScriptRepository(context: RepositoryScanContext): Promise<boolean> {
  const rootEntries = new Set(
    (await context.readDirectoryEntries(context.repoRoot)).map((entry) => entry.name),
  );
  return ["package.json", "tsconfig.json", "jsconfig.json"].some((fileName) =>
    rootEntries.has(fileName),
  );
}

function barrelFileLooksGenerated(content: string): boolean {
  const prelude = content.split(/\r?\n/).slice(0, 5).join("\n");
  return /generated file|auto-generated|autogenerated|do not edit/i.test(prelude);
}

function buildBarrelSuggestion(relativePath: string, generated: boolean): string {
  if (relativePath.endsWith(".d.ts")) {
    return "Review the flagged declaration barrel carefully. Keep broad re-exports when they define a public type surface, and only narrow them when the declaration entrypoint is not intentionally serving that API boundary.";
  }

  if (generated) {
    return "Review the flagged generated barrel carefully. Prefer changing the generator or upstream source shape instead of hand-editing generated `export *` output, and only narrow the barrel if that workflow is safe for regeneration.";
  }

  return "Replace broad `export *` barrel usage in the flagged file with direct imports or narrower explicit re-exports, then consider adding `no-barrel-file` to keep large barrels from returning.";
}

function buildBarrelAiHandoff(relativePath: string, generated: boolean): string {
  if (relativePath.endsWith(".d.ts")) {
    return `Review ${relativePath} as a large declaration barrel. Keep public API entrypoints intact, and only narrow broad \`export *\` re-exports when the declaration surface is not intentionally exposed as that API boundary.`;
  }

  if (generated) {
    return `Review ${relativePath} as a generated large barrel. Prefer fixing the generator or upstream source layout instead of hand-editing generated output, and only narrow broad \`export *\` re-exports when regeneration stays safe.`;
  }

  return `Review ${relativePath} and remove broad \`export *\` barrel patterns that Oxlint flagged as oversized. Keep API boundaries narrow, prefer direct imports where possible, and evaluate adding \`no-barrel-file\` as a guardrail.`;
}

export async function collectLargeBarrelFileDiagnostics(
  repoRoot: string,
  repository: RepositorySignals,
  warnings?: AnalysisWarning[],
  scanContext?: RepositoryScanContext,
): Promise<Diagnostic[]> {
  const context = scanContext ?? new RepositoryScanContext(repoRoot, warnings ?? []);
  if (!(await looksLikeJavaScriptRepository(context))) {
    return [];
  }

  if (
    repository.eslint.usesOxlint ||
    repository.eslint.usesNoBarrelFilesPlugin ||
    repository.eslint.usesBarrelFilesPlugin
  ) {
    return [];
  }

  if (repository.workflowCount === 0 || !repository.primaryWorkflowPath) {
    return [];
  }

  const barrelDiagnostics = await collectEmbeddedOxlintDiagnosticsByCode(
    repoRoot,
    "oxc(no-barrel-file)",
    warnings,
  );
  if (!barrelDiagnostics) {
    return [];
  }

  const results = await Promise.allSettled(
    barrelDiagnostics.map(async ({ diagnostic, relativePath }) => {
      const contextText = diagnostic.message;
      const fileContent = (await context.readTextFileOrWarn(context.resolve(relativePath))) ?? "";
      const generated = barrelFileLooksGenerated(fileContent);
      const advisoryOnly = generated || relativePath.endsWith(".d.ts");
      const why =
        "Embedded Oxlint `oxc/no-barrel-file` detected a large `export *` barrel. Large barrel files can inflate module graph construction cost for CI lint, test, typecheck, and build steps.";
      const suggestion = buildBarrelSuggestion(relativePath, generated);

      const builtDiagnostic = buildRepositoryDiagnostic(repository, barrelFileMeta, {
        location: {
          path: relativePath,
          line: diagnostic.line,
          column: diagnostic.column,
        },
        severity: undefined,
        message: `Embedded Oxlint scan flagged ${relativePath} as a large barrel file. ${contextText}`,
        why,
        suggestion,
        measurementHint:
          "Compare lint, test, typecheck, or build wall-clock time before and after replacing the flagged barrel with direct imports or narrower re-exports.",
        aiHandoff: buildBarrelAiHandoff(relativePath, generated),
        score: 92,
      });
      const ops: DiagnosticOp[] = advisoryOnly
        ? [
            { op: "setSeverity", severity: "suggestion" },
            { op: "setScore", score: 36 },
          ]
        : [];
      return applyOps(builtDiagnostic, ops);
    }),
  );

  const fulfilled: Diagnostic[] = [];
  for (const result of results) {
    if (result.status === "fulfilled") {
      fulfilled.push(result.value);
    }
  }
  return fulfilled;
}
