name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: success()
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
        timeout-minutes: 10
