export type RuleIdKind = "workflow" | "repository";

export interface RegisteredRuleEntry {
  readonly kind: RuleIdKind;
}

export const RULE_REGISTRY: Record<string, RegisteredRuleEntry> = {
  "avoid-broad-upload-artifact": { kind: "workflow" },
  "avoid-brew-update-on-hosted-macos": { kind: "workflow" },
  "avoid-c-drive-on-windows-runner": { kind: "workflow" },
  "avoid-docker-image-via-uses": { kind: "workflow" },
  "avoid-eslint-plugin-prettier": { kind: "workflow" },
  "avoid-prettier-eslint": { kind: "workflow" },
  "avoid-xcode-install-on-hosted-macos": { kind: "workflow" },
  "cache-terraform-providers": { kind: "workflow" },
  "cargo-build-before-test": { kind: "workflow" },
  "circleci-checkout-uses-full-clone": { kind: "workflow" },
  "collapse-multiple-go-builds-in-job": { kind: "workflow" },
  "consider-caching-os-packages-or-using-a-custom-image": { kind: "workflow" },
  "consider-filter-blob-none-for-release-metadata": { kind: "workflow" },
  "consider-slim-over-alpine-for-ci": { kind: "workflow" },
  "db-io-reduce": { kind: "workflow" },
  "deep-checkout-excessive-depth": { kind: "workflow" },
  "deep-checkout-without-need": { kind: "workflow" },
  "docker-bake-file-unused-in-ci": { kind: "workflow" },
  "docker-build-cache-disabled-in-ci": { kind: "workflow" },
  "docker-build-load-true-unnecessary": { kind: "workflow" },
  "docker-build-without-layer-cache": { kind: "workflow" },
  "duplicate-checkout-in-same-workflow": { kind: "workflow" },
  "duplicate-install-or-lint": { kind: "workflow" },
  "elixir-otp-version-performance": { kind: "workflow" },
  "go-build-before-race-test": { kind: "workflow" },
  "go-test-broad-package-serial-p-one": { kind: "workflow" },
  "go-test-repeats-vet-after-go-vet": { kind: "workflow" },
  "hatch-without-uv-installer": { kind: "workflow" },
  "missing-angular-cli-cache": { kind: "workflow" },
  "missing-concurrency": { kind: "workflow" },
  "missing-dependency-cache": { kind: "workflow" },
  "missing-gradle-build-cache": { kind: "workflow" },
  "missing-make-j-flag": { kind: "workflow" },
  "missing-next-build-cache": { kind: "workflow" },
  "missing-path-ignore-for-non-code": { kind: "workflow" },
  "missing-paths-filter": { kind: "workflow" },
  "missing-release-downstream-success-guard": { kind: "workflow" },
  "missing-test-worker-tuning-for-standard-runner": { kind: "workflow" },
  "missing-timeout-in-minutes-buildkite": { kind: "workflow" },
  "missing-timeout-in-minutes-gitlab-ci": { kind: "workflow" },
  "missing-timeout-minutes": { kind: "workflow" },
  "missing-turbo-cache": { kind: "workflow" },
  "matrix-test-job-without-test-sharding": { kind: "workflow" },
  "native-dependency-may-fall-back-to-source-build": { kind: "workflow" },
  "npm-audit-in-ci": { kind: "workflow" },
  "nox-without-uv-backend": { kind: "workflow" },
  "prefer-npm-ci": { kind: "workflow" },
  "outdated-datadog-lambda-extension": { kind: "workflow" },
  "outdated-setup-action-without-cache": { kind: "workflow" },
  "pdm-without-use-uv": { kind: "workflow" },
  "prefer-buildx-bake-for-multiple-images": { kind: "workflow" },
  "prefer-buildx-build-over-docker-build": { kind: "workflow" },
  "prefer-direct-upload-for-compressed-artifacts": { kind: "workflow" },
  "prefer-dorny-paths-filter-for-scoped-jobs": { kind: "workflow" },
  "prefer-frozen-lockfile": { kind: "workflow" },
  "prefer-jest-30-for-jest-29": { kind: "workflow" },
  "prefer-lefthook-for-complex-git-hooks": { kind: "workflow" },
  "prefer-native-arm-runner-over-qemu": { kind: "workflow" },
  "prefer-nextest-for-heavy-rust-tests": { kind: "workflow" },
  "prefer-nextjs-12-minor-performance-milestone": { kind: "workflow" },
  "prefer-nextjs-13-minor-performance-milestone": { kind: "workflow" },
  "prefer-nextjs-14-minor-performance-milestone": { kind: "workflow" },
  "prefer-oxlint-over-eslint": { kind: "workflow" },
  "prefer-oxfmt-over-prettier": { kind: "workflow" },
  "prefer-rails-performance-milestone": { kind: "workflow" },
  "prefer-ruff-format-over-black": { kind: "workflow" },
  "prefer-ruff-import-sorting-over-isort": { kind: "workflow" },
  "prefer-setup-bun-for-lightweight-node-tooling": { kind: "workflow" },
  "prefer-setup-uv-for-lightweight-python-tooling": { kind: "workflow" },
  "prefer-sparse-checkout-for-scoped-workflow": { kind: "workflow" },
  "prefer-standard-arm-runner-for-api-cli": { kind: "workflow" },
  "prefer-standard-arm-runner-for-portable-tooling": { kind: "workflow" },
  "prefer-storybook-6-minor-performance-milestone": { kind: "workflow" },
  "prefer-storybook-7-minor-performance-milestone": { kind: "workflow" },
  "prefer-tailwind-v4-upgrade-tool": { kind: "workflow" },
  "prefer-uv-pip-over-pip": { kind: "workflow" },
  "prefer-zstd-compression-for-pushed-docker-images": { kind: "workflow" },
  "rails-db-schema-load-over-migrate": { kind: "workflow" },
  "prefer-ruby-33-yjit": { kind: "workflow" },
  "redundant-install-for-preinstalled-cli": { kind: "workflow" },
  "redundant-manual-cache-with-setup-action": { kind: "workflow" },
  "redundant-npx-or-bootstrap": { kind: "workflow" },
  "repeated-bootstrap-setup": { kind: "workflow" },
  "repeated-build-in-same-workflow": { kind: "workflow" },
  "repeated-install-in-same-job": { kind: "workflow" },
  "repeated-lint-in-same-workflow": { kind: "workflow" },
  "ruby-setup-ruby-missing-bundler-cache": { kind: "workflow" },
  "scheduled-heavy-workflow-without-throttling": { kind: "workflow" },
  "tox-without-tox-uv": { kind: "workflow" },
  "ungated-heavy-job": { kind: "workflow" },
  "unnecessary-app-install-for-lint-job": { kind: "workflow" },
  "unnecessary-checkout-when-only-using-artifacts": { kind: "workflow" },
  "unnecessary-npm-global-upgrade-before-npm-install": { kind: "workflow" },
  "wasteful-npm-global-install": { kind: "workflow" },
  "wasteful-package-install-in-container": { kind: "workflow" },
  "prefer-node-run-over-npm-run": { kind: "repository" },
  "setup-node-cache-dependency-path-unset": { kind: "repository" },
  "gradle-parallel-not-enabled": { kind: "repository" },
} as const;

export type RegisteredRuleId = keyof typeof RULE_REGISTRY;

export function isRegisteredRuleId(id: string): id is RegisteredRuleId {
  return id in RULE_REGISTRY;
}
